apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2025-01-08T00:05:56Z","generation":1,"labels":{"app":"synergychat-api"},"name":"synergychat-api","namespace":"default","resourceVersion":"568994","uid":"d679d904-c9a1-4929-9726-ac7e7ccf8866"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"synergychat-api"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"synergychat-api"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"synergychat-api-configmap"}}],"image":"docker.io/bootdotdev/synergychat-api:latest","imagePullPolicy":"Always","name":"synergychat-api","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/persist","name":"synergychat-api-volume"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"synergychat-api-volume","persistentVolumeClaim":{"claimName":"synergychat-api-pvc"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2025-01-08T00:05:56Z","lastUpdateTime":"2025-01-08T00:05:59Z","message":"ReplicaSet \"synergychat-api-9c65b97cd\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2025-01-08T00:07:22Z","lastUpdateTime":"2025-01-08T00:07:22Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2025-01-08T00:05:56Z"
  generation: 2
  labels:
    app: synergychat-api
  name: synergychat-api
  namespace: default
  resourceVersion: "569155"
  uid: d679d904-c9a1-4929-9726-ac7e7ccf8866
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: synergychat-api
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: synergychat-api-configmap
        image: docker.io/bootdotdev/synergychat-api:latest
        imagePullPolicy: Always
        name: synergychat-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /persist
          name: synergychat-api-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: synergychat-api-volume
        persistentVolumeClaim:
          claimName: synergychat-api-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-01-08T00:05:56Z"
    lastUpdateTime: "2025-01-08T00:05:59Z"
    message: ReplicaSet "synergychat-api-9c65b97cd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-01-08T00:07:22Z"
    lastUpdateTime: "2025-01-08T00:07:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
